config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :model_orders,      only: [:index, :create]
  resources :photoshoot_orders, only: [:index, :create]

  get '/finish', to: 'main#finish'

  namespace :admin do
    resources :orders,            only: [:index]
    resources :photoshoot_orders, only: [:show, :destroy]
    resources :model_orders,      only: [:show, :destroy]

    root to: 'orders#index'
  end

  root 'main#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  devise :database_authenticatable, :rememberable
end

app/models/model_order.rb
class ModelOrder < ActiveRecord::Base

  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :name,    presence: true
  validates :email,   presence: true
  validates :message, presence: true

  def type
    'TFP request'
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  has_attached_file :image

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/photoshoot_order.rb
class PhotoshootOrder < ActiveRecord::Base

  validates :name,    presence: true
  validates :email,   presence: true
  validates :message, presence: true

  def type
    'Photoshoot order'
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  before_action :authenticate_admin!
end

app/controllers/admin/model_orders_controller.rb
class Admin::ModelOrdersController < Admin::AdminController

  def show
    @model_order = ModelOrder.find(params[:id])
  end

  def destroy
    ModelOrder.find(params[:id]).destroy!
    flash[:success] = 'Order successfully deleted'
    redirect_to admin_orders_path
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController

  def index
    scope = PhotoshootOrder.all + ModelOrder.all
    scope = scope.sort_by { |order| order.created_at }.reverse

    @orders = scope
  end
end

app/controllers/admin/photoshoot_orders_controller.rb
class Admin::PhotoshootOrdersController < Admin::AdminController

  def show
    @photoshoot_order = PhotoshootOrder.find(params[:id])
  end

  def destroy
    PhotoshootOrder.find(params[:id]).destroy!
    flash[:success] = 'Order successfully deleted'
    redirect_to admin_orders_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def layout_by_resource
    devise_controller? ? 'devise' : 'application'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

  def finish
  end
end

app/controllers/model_orders_controller.rb
class ModelOrdersController < ApplicationController

  def index
    @model_order = ModelOrder.new
  end

  def create
    @model_order = ModelOrder.new(model_order_params)

    if @model_order.save
      redirect_to finish_path
    else
      render :index
    end
  end

  private

  def model_order_params
    params.require(:model_order).permit(:name, :email, :message,
                   photos_attributes: [:id, :image])
  end
end

app/controllers/photoshoot_orders_controller.rb
class PhotoshootOrdersController < ApplicationController

  def index
    @photoshoot_order = PhotoshootOrder.new
  end

  def create
    @photoshoot_order = PhotoshootOrder.new(photoshoot_order_params)

    if @photoshoot_order.save
      redirect_to finish_path
    else
      render :index
    end
  end

  private

  def photoshoot_order_params
    params.require(:photoshoot_order).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/model_orders/show.html.slim
.container.admin_model_order

  p= "#{@model_order.type} from: #{@model_order.name}, #{l @model_order.created_at, format: :short}, email: #{@model_order.email}"
  br
  - @model_order.photos.each do |photo|
    = link_to photo.image.url, target: '_blank' do
      = image_tag photo.image.url
  br
  br
  p= @model_order.message

  = link_to 'Back', admin_orders_path, class: 'btn btn-default back'

app/views/admin/orders/index.html.slim
.container.orders
  table.table
    thead
      tr
        th Type
        th Name
        th Email
        th Message
        th Created at
        th
    tbody
      - @orders.each do |order|
        tr
          td= order.type
          td= link_to order.name, [:admin, order]
          td= order.email
          td= order.message
          td= l order.created_at, format: :short
          td
            => link_to 'Show', [:admin, order], class: 'btn btn-success'
            = link_to 'Delete', [:admin, order], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }

app/views/admin/photoshoot_orders/show.html.slim
.container.admin_photoshoot_order

  p= "#{@photoshoot_order.type} from: #{@photoshoot_order.name}, #{l @photoshoot_order.created_at, format: :short}, email: #{@photoshoot_order.email}"
  br
  p= @photoshoot_order.message

  = link_to 'Back', admin_orders_path, class: 'btn btn-default back'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Lighthousing
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  body
    .container
      = render 'shared/menu'
      = render 'shared/flashes'
      = yield

    = javascript_include_tag 'application'

app/views/layouts/devise.html.slim
doctype html
html
  head
    title Lighthousing
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  body
    .container.devise
      = yield

    = javascript_include_tag 'application'

app/views/main/finish.html.slim
.container.finish
  = image_tag 'finish.jpg'
  = link_to 'Back to LIGHTHOUSING', 'http://lighthousing.eu'

app/views/main/index.html.slim
.container.main
  .row
    h1 I'd like to..
  .row
    = link_to model_orders_path do
      .option.model
    = link_to photoshoot_orders_path do
      .option.photoshoot
    p.order= link_to 'Be a model (TFP)', model_orders_path
    p.order= link_to 'Order a photoshoot', photoshoot_orders_path

app/views/model_orders/_form.html.slim
.form
  = simple_nested_form_for model_order do |f|
    = f.error_notification
    = f.input :name
    = f.input :email
    = f.fields_for :photos do |photo|
      = photo.input :image, label: false
      = photo.link_to_remove 'Remove photo', class: 'btn btn-xs btn-warning'
      br
      br
      br
    br
    = f.link_to_add 'Add new photo', :photos, class: 'btn btn-info pull-right'
    br
    br
    = f.input :message
    = f.submit 'Send request', class: 'btn btn-big btn-primary'

app/views/model_orders/index.html.slim
.container.model_order

  = link_to image_url('model_1.jpg'), target: '_blank' do
    = image_tag 'model_1.jpg'
  = link_to image_url('model_2.jpg'), target: '_blank' do
    = image_tag 'model_2.jpg'
  = link_to image_url('model_3.jpg'), target: '_blank' do
    = image_tag 'model_3.jpg'

  = link_to image_url('model_4.jpg'), target: '_blank' do
    = image_tag 'model_4.jpg'
  = link_to image_url('model_5.jpg'), target: '_blank' do
    = image_tag 'model_5.jpg'
  = link_to image_url('model_6.jpg'), target: '_blank' do
    = image_tag 'model_6.jpg'

  br
  br

  .info
    p I'm always looking for new interesting faces. Maybe, exactly You will be next?

  = render 'form', model_order: @model_order

  br
  = link_to 'Back', root_path, class: 'btn'

app/views/photoshoot_orders/_form.html.slim
.form
  = simple_form_for photoshoot_order do |f|
    = f.error_notification
    = f.input :name
    = f.input :email
    = f.input :message
    = f.submit 'Send request', class: 'btn btn-big btn-primary'

app/views/photoshoot_orders/index.html.slim
.container.photoshoot_order

  = link_to image_url('photoshoot_1.jpg'), target: '_blank' do
    = image_tag 'photoshoot_1.jpg'
  = link_to image_url('photoshoot_2.jpg'), target: '_blank' do
    = image_tag 'photoshoot_2.jpg'
  = link_to image_url('photoshoot_3.jpg'), target: '_blank' do
    = image_tag 'photoshoot_3.jpg'

  = link_to image_url('photoshoot_4.jpg'), target: '_blank' do
    = image_tag 'photoshoot_4.jpg'
  = link_to image_url('photoshoot_5.jpg'), target: '_blank' do
    = image_tag 'photoshoot_5.jpg'
  = link_to image_url('photoshoot_6.jpg'), target: '_blank' do
    = image_tag 'photoshoot_6.jpg'

  br
  br

  .info
    p  - portrait photoshoot (1,5 - 2 hours, 20 or more retouched photos, 1500czk)
    p - bussines portrait (1 hour, 10 retouched photos, 800czk)
    p - love story (1,5 - 2 hours, 25 or more retouched photos, 2000czk)
    p Location: Czech Republic Brno

  = render 'form', photoshoot_order: @photoshoot_order

  br
  = link_to 'Back', root_path, class: 'btn'

app/views/shared/_flashes.html.slim
#flash.flashmessage
  - flash.each do |key, value|
    div.container class="alert alert-#{ key }"
      = value

app/views/shared/_menu.html.slim
.navbar.navbar-static-top
  .navbar-inner
    .container
      = link_to 'Lighthousing for You', root_path, class: 'brand'
      ul.nav
        li= link_to '​Back to the blog', 'http://www.lighthousing.eu/en/', target: '_self'
        li= link_to 'Facebook', 'http://facebook.com/lighthousing.eu', target: '_blank'
        li= link_to '​Vkontakte​­', 'http://vk.com/club68707545', target: '_blank'
        li= link_to 'Instagram', 'http://instagram.com/lighthousing', target: '_blank'
        - if admin_signed_in?
          li= link_to 'Admin', admin_root_path
          li= link_to 'Log out', destroy_admin_session_path, method: :delete

      ul.nav.right.pull-right
        - unless admin_signed_in?
          li= link_to 'Sign in', admin_root_path